package cn.mldn.ssm.dao.table.entity;

import java.io.Serializable;

public class Dept implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptId
     *
     * @mbg.generated
     */
    private Integer deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptNo
     *
     * @mbg.generated
     */
    private String deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptName
     *
     * @mbg.generated
     */
    private String deptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.emps
     *
     * @mbg.generated
     */
    private Integer emps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptId
     *
     * @return the value of dept.deptId
     *
     * @mbg.generated
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptId
     *
     * @param deptid the value for dept.deptId
     *
     * @mbg.generated
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptNo
     *
     * @return the value of dept.deptNo
     *
     * @mbg.generated
     */
    public String getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptNo
     *
     * @param deptno the value for dept.deptNo
     *
     * @mbg.generated
     */
    public void setDeptno(String deptno) {
        this.deptno = deptno == null ? null : deptno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptName
     *
     * @return the value of dept.deptName
     *
     * @mbg.generated
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptName
     *
     * @param deptname the value for dept.deptName
     *
     * @mbg.generated
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname == null ? null : deptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.emps
     *
     * @return the value of dept.emps
     *
     * @mbg.generated
     */
    public Integer getEmps() {
        return emps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.emps
     *
     * @param emps the value for dept.emps
     *
     * @mbg.generated
     */
    public void setEmps(Integer emps) {
        this.emps = emps;
    }

   

	@Override
	public String toString() {
		return "Dept [deptid=" + deptid + ", deptno=" + deptno + ", deptname=" + deptname + ", emps=" + emps + "]";
	}
    
}